version: "2"
services:
  api:
    build: ./api_v1
    volumes:
        - C:\Users\alexa\Dvideos:/videos
    ports: 
        - "2224:5000"
    depends_on:
        - "mosquitto-mqtt"
  #sftp:
    #build: ./sftp/
    #volumes:
    #    - ./videos:/home/ORV/videos
    #ports:
   #     - "2223:22"
    #command:
     #   - ORV:password:1001
  mosquitto-mqtt:
    image: eclipse-mosquitto:latest 
    volumes:
        - ./mosquittoMqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
        - "2222:1883"
        - "2225:9006"
volumes:
  videos:
